"""Intelligent Metadata Extractor for RAG Ingestion.

Implements Schema-Guided LLM Metadata Enrichment and Attribution for unstructured
spiritual discourse transcripts, videos, and articles.

Design Architecture & Invariants:
---------------------------------
1. Domain & Lineage Unity:
   In AskMukthiGuru, the core spiritual wisdom is expounded by Sri Preethaji & Sri Krishnaji
   (Ekam / O&O Academy). Because Sri Krishnaji and Sri Preethaji co-create Ekam, co-authored
   'The Four Sacred Secrets', and co-guide practices (such as Soul Sync, Serene Mind, and Deeksha),
   teachings in this corpus belong to their shared spiritual heritage.
   Therefore, `attributed_teacher_ids` retains both gurus (['preethaji', 'krishnaji']) for all
   Ekam teachings, ensuring unified retrieval access while preserving specific speaker attribution.

2. Ingestion Safety (AGENTS.md Invariant 1):
   Every string generated by the LLM (context headers, themes, summaries) MUST pass
   `services.text_quality_filter.find_artifact()` to ensure no CoT leakage, provider
   canned error degradation messages, or corrupt tokens ever reach vector persistence.

3. Resilience & Graceful Fallback:
   If the LLM provider is unavailable, times out, or returns unparseable JSON, the extractor
   gracefully falls back to deterministic domain heuristics without breaking the ingestion pipeline.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from app.config import settings
from services.text_quality_filter import find_artifact

logger = logging.getLogger(__name__)


@dataclass
class IntelligentMetadata:
    """Structured, enriched metadata for a chunk or document."""

    primary_teacher_id: str
    attributed_teacher_ids: List[str]
    speakers: List[str]
    practices: List[str]
    core_themes: List[str]
    context_header: str
    confidence: float = 1.0
    rationale: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


_SYSTEM_PROMPT = """\
You are an expert spiritual ontology classifier and metadata extractor for the Mukthi Guru knowledge base.
Your role is to analyze a spiritual teaching transcript chunk and extract structured metadata in strict JSON.

### Domain Lineage & Guru Knowledge:
- Core Gurus: Sri Krishnaji and Sri Sri Preethaji (creators of Ekam / O&O Academy, authors of 'The Four Sacred Secrets').
- Even when one guru is the primary speaker in a discourse, their wisdom forms part of their shared Ekam lineage.
- Other lineages (e.g. Sri Amma Bhagavan, Sadhguru, ISKCON) should only be attributed if explicitly referenced as the teaching origin.
- Do NOT confuse references to Sri Krishnaji with ISKCON/Krishna, or mentions of 'Oneness'/'Deeksha' with third-party lineages.

### Required JSON Output Schema:
{
  "primary_teacher_id": "krishnaji" | "preethaji" | "preethaji_krishnaji" | "ekam" | "amma_bhagavan" | "other",
  "attributed_teacher_ids": ["preethaji", "krishnaji"],
  "speakers": ["Sri Krishnaji"],
  "practices": ["Soul Sync", "Serene Mind"],
  "core_themes": ["truth_of_suffering", "consciousness", "karma", "inner_stillness"],
  "context_header": "1-2 sentence concise summary situating the chunk within the discourse for search retrieval",
  "confidence": 0.95,
  "rationale": "Brief justification for the attribution"
}

Respond ONLY with valid JSON. Do not include markdown codeblocks or conversational preamble.
"""

_USER_PROMPT_TEMPLATE = """\
<source_context>
Title: {title}
Speaker/Channel: {speaker}
Source URL: {source_url}
</source_context>

<chunk_content>
{chunk_text}
</chunk_content>

Extract the structured spiritual metadata according to the instructions.
"""


class IntelligentMetadataExtractor:
    """
    Service for extracting structured teacher attribution, doctrinal themes,
    and contextual headers using foundation model intelligence.
    """

    def __init__(self, llm_service: Optional[Any] = None) -> None:
        self._llm = llm_service

    def _get_llm(self) -> Any:
        if self._llm is not None:
            return self._llm
        try:
            from services.llm_factory import LLMServiceFactory
            provider = getattr(settings, "llm_provider", "openrouter")
            self._llm = LLMServiceFactory.create(provider)
        except Exception as e:
            logger.warning(f"Could not initialize default LLM in IntelligentMetadataExtractor: {e}")
            self._llm = None
        return self._llm

    async def extract_metadata(
        self,
        chunk_text: str,
        title: str = "",
        speaker: str = "",
        source_url: str = "",
        tags: Optional[List[str]] = None,
    ) -> IntelligentMetadata:
        """
        Extract structured metadata and contextual positioning for a chunk.
        
        Guaranteed to return a valid IntelligentMetadata instance even if LLM fails.
        """
        llm = self._get_llm()
        if llm is None:
            return self._fallback_extraction(chunk_text, title, speaker, source_url, tags)

        user_prompt = _USER_PROMPT_TEMPLATE.format(
            title=title or "Spiritual Discourse",
            speaker=speaker or "Unknown",
            source_url=source_url or "",
            chunk_text=chunk_text[:3000],
        )

        try:
            raw_response = await llm.generate(
                system_prompt=_SYSTEM_PROMPT,
                user_prompt=user_prompt,
                temperature=0.0,
                operation="intelligent_metadata_extraction",
            )
            
            # 1. Ingestion Safety Invariant 1: Check for contamination / CoT leaks
            artifact = find_artifact(raw_response)
            if artifact:
                logger.warning(f"LLM metadata response rejected by safety filter: {artifact}")
                return self._fallback_extraction(chunk_text, title, speaker, source_url, tags)

            # 2. Parse JSON
            cleaned = raw_response.strip()
            if cleaned.startswith("```"):
                cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
                cleaned = re.sub(r"\s*```$", "", cleaned)
                cleaned = cleaned.strip()

            data = json.loads(cleaned)

            # 3. Validate and sanitize fields
            primary_id = str(data.get("primary_teacher_id", "ekam")).lower().strip()
            if primary_id not in ("krishnaji", "preethaji", "preethaji_krishnaji", "ekam", "amma_bhagavan", "other"):
                primary_id = "ekam"

            attr_ids = data.get("attributed_teacher_ids")
            if not isinstance(attr_ids, list) or not attr_ids:
                attr_ids = ["preethaji", "krishnaji"]
            else:
                attr_ids = [str(x).lower().strip() for x in attr_ids if x]
                # Ensure Ekam teachings maintain joint teacher availability
                if primary_id in ("krishnaji", "preethaji", "preethaji_krishnaji", "ekam"):
                    if "preethaji" not in attr_ids:
                        attr_ids.append("preethaji")
                    if "krishnaji" not in attr_ids:
                        attr_ids.append("krishnaji")

            context_hdr = str(data.get("context_header", "")).strip()
            if context_hdr:
                header_artifact = find_artifact(context_hdr)
                if header_artifact:
                    context_hdr = ""

            return IntelligentMetadata(
                primary_teacher_id=primary_id,
                attributed_teacher_ids=attr_ids,
                speakers=[str(s) for s in data.get("speakers", []) if s],
                practices=[str(p) for p in data.get("practices", []) if p],
                core_themes=[str(t).lower().replace(" ", "_") for t in data.get("core_themes", []) if t],
                context_header=context_hdr,
                confidence=float(data.get("confidence", 0.9)),
                rationale=str(data.get("rationale", "llm_structured_extraction")),
            )

        except Exception as exc:
            logger.warning(f"Intelligent metadata extraction failed, falling back: {exc}")
            return self._fallback_extraction(chunk_text, title, speaker, source_url, tags)

    def _fallback_extraction(
        self,
        chunk_text: str,
        title: str,
        speaker: str,
        source_url: str,
        tags: Optional[List[str]],
    ) -> IntelligentMetadata:
        """Deterministic heuristic fallback when LLM is unreachable."""
        from services.teacher_attribution import resolve_teacher_attribution

        _, primary_id, attr_ids = resolve_teacher_attribution(
            title=title,
            source_url=source_url,
            speaker=speaker,
            chunks=[chunk_text],
            tags=tags,
        )

        speakers = []
        if primary_id == "krishnaji":
            speakers = ["Sri Krishnaji"]
        elif primary_id == "preethaji":
            speakers = ["Sri Preethaji"]
        elif primary_id in ("preethaji_krishnaji", "ekam"):
            speakers = ["Sri Preethaji & Sri Krishnaji"]

        context_hdr = ""
        if title:
            context_hdr = f"Discourse on {title} by {', '.join(speakers) if speakers else 'Ekam Gurus'}."

        return IntelligentMetadata(
            primary_teacher_id=primary_id,
            attributed_teacher_ids=attr_ids,
            speakers=speakers,
            practices=[],
            core_themes=[],
            context_header=context_hdr,
            confidence=0.8,
            rationale="heuristic_fallback",
        )
