import { z } from 'zod';
import type { AnswerEvidence, BackendMetadata, Citation, GuidancePlan, GroundingState, LiveLogisticsEvent, ProactiveSereneMindTrigger } from './chat/types';
import { supabase } from '@/integrations/supabase/client';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { SupportedStorage } from '@supabase/supabase-js';

const isNative = typeof Capacitor !== 'undefined' && Capacitor.isNativePlatform();

const storage: SupportedStorage = isNative
  ? {
      async getItem(key: string) { return (await Preferences.get({ key }))?.value ?? null; },
      async setItem(key: string, value: string) { await Preferences.set({ key, value }); },
      async removeItem(key: string) { await Preferences.remove({ key }); },
    }
  : {
      getItem(key: string) { return Promise.resolve(localStorage.getItem(key)); },
      setItem(key: string, value: string) { localStorage.setItem(key, value); return Promise.resolve(); },
      removeItem(key: string) { localStorage.removeItem(key); return Promise.resolve(); },
    };

const LOCAL_CHAT_KEYS = [
  'askmukthiguru_chat_history',
  'askmukthiguru_conversations',
  'askmukthiguru_current_conversation',
  'askmukthiguru_feedback',
  'askmukthiguru_max_conversations',
  'askmukthiguru_retention_days',
] as const;

/**
 * Remove locally cached conversation and feedback content on identity changes.
 * This is intentionally storage-adapter based so native Preferences are purged
 * too; callers should await it before presenting the next signed-in session.
 */
export const clearLocalChatData = async (): Promise<void> => {
  await Promise.all(LOCAL_CHAT_KEYS.map((key) => storage.removeItem(key)));
};

export interface MessageFeedback {
  vote: 'up' | 'down';
  tags: string[];
  comment?: string;
  timestamp: Date;
}

export type MessageErrorKind = 'network' | 'unauthorized' | 'rate_limited' | 'quota_exceeded' | 'server_error' | 'timeout' | 'connection_refused' | 'dns_failure' | 'backend_down' | 'telemetry_failed' | 'circuit_breaker' | 'unknown';

export interface MessageError {
  kind: MessageErrorKind;
  title: string;
  description: string;
  /** Suggested user action surfaced as a button in the error bubble. */
  actionLabel?: 'retry' | 'sign_in' | 'reload';
  /** Optional technical detail (status code, message) shown in a details disclosure. */
  detail?: string;
}

export interface Message {
  id: string;
  role: 'user' | 'guru';
  content: string;
  timestamp: Date;
  citations?: Citation[];
  confidenceScore?: number;
  /** E3.2 one-line explainable reason for the confidence score (optional, forward-compat). */
  confidenceReason?: string;
  /** Requested language of this message’s rendered content (BCP-47 or base code). */
  language?: string;
  feedback?: MessageFeedback;
  /** Memory facts the backend retrieved and used to ground this guru reply. */
  memoriesUsed?: string[];
  /** Non-null when this guru bubble represents a failed response (network/auth/server). */
  error?: MessageError;
  /** Follow-up suggestion questions generated by the backend. */
  followUpSuggestions?: string[];
  /** A consent-based Serene Mind offer shown after the teaching response. */
  sereneMindOffer?: ProactiveSereneMindTrigger | null;
  /** Time-bounded event, booking, or schedule information from official sources. */
  liveLogisticsEvents?: LiveLogisticsEvent[];
  /** Structured, optional UI guidance; never derived from answer prose. */
  guidancePlan?: GuidancePlan | null;
  /** Evidence provenance accompanying a guru reply. */
  answerEvidence?: AnswerEvidence | null;
  groundingState?: GroundingState;
  faithfulnessScore?: number | null;
  relevancyScore?: number | null;
  hallucinationFlag?: boolean | null;
  verification?: BackendMetadata | null;
  citationsVerified?: boolean | null;
  orphanCitationsStripped?: boolean | null;
  releaseManifest?: BackendMetadata | null;
  provenanceManifest?: BackendMetadata | null;
  aiProvenance?: BackendMetadata | null;
  traceId?: string | null;
  latencyMs?: number | null;
  modelUsed?: string | null;
  modelProvider?: string | null;
  queryTier?: string | null;
}

// ── Feedback helpers ──────────────────────────────────────────────
const FEEDBACK_KEY = 'askmukthiguru_feedback';

export const saveFeedback = (messageId: string, feedback: MessageFeedback): void => {
  if (_incognito) return;
  try {
    const all = loadAllFeedback();
    all[messageId] = feedback;
    localStorage.setItem(FEEDBACK_KEY, JSON.stringify(all));
  } catch (e) {
    console.error('Failed to save feedback:', e);
  }
};

// ── Zod schemas for safe deserialization ─────────────────────────
// Citations used to be stored as bare URL strings; accept both shapes so
// existing local history (pre-title-threading) doesn't fail parsing and get
// wiped by the "corrupted conversations — clearing" fallback below.
const CitationSchema = z.union([
  z.string().transform((url) => ({ url })),
  z.object({ url: z.string(), title: z.string().nullable().optional() }),
]);

const MessageSchema = z.object({
  id: z.string(),
  role: z.enum(['user', 'guru']),
  content: z.string(),
  timestamp: z.coerce.date(),
  citations: z.array(CitationSchema).optional(),
  language: z.string().optional(),
  confidenceScore: z.number().optional(),
  confidenceReason: z.string().optional(),
  feedback: z.object({
    vote: z.enum(['up', 'down']),
    tags: z.array(z.string()),
    comment: z.string().optional(),
    timestamp: z.coerce.date(),
  }).optional(),
  memoriesUsed: z.array(z.string()).optional(),
  liveLogisticsEvents: z.array(z.object({
    event_name: z.string(),
    official_source_url: z.string().url(),
    booking_url: z.string().url().nullable().optional(),
    verified_at: z.string(),
    expires_at: z.string(),
  })).optional(),
  guidancePlan: z.object({
    response_mode: z.string(),
    language: z.string(),
    attribution: z.object({ label: z.string(), source_backed: z.boolean(), teacher_name: z.string().nullable().optional() }),
    action_step: z.object({ title: z.string(), instruction: z.string(), optional: z.boolean(), safety_note: z.string().nullable().optional() }).nullable().optional(),
    reflection_prompt: z.string().nullable().optional(),
  }).nullable().optional(),
  answerEvidence: z.object({
    corpus_id: z.string(),
    release_version: z.number().nullable().optional(),
    model_policy_id: z.string(),
    evidence_support_label: z.string(),
    source_count: z.number(),
    top_source_score: z.number().nullable().optional(),
    citations_verified: z.boolean().nullable().optional(),
  }).nullable().optional(),
  groundingState: z.enum(['grounded', 'abstained', 'safety_redirect', 'system_error']).optional(),
  faithfulnessScore: z.number().nullable().optional(),
  relevancyScore: z.number().nullable().optional(),
  hallucinationFlag: z.boolean().nullable().optional(),
  verification: z.record(z.string(), z.unknown()).nullable().optional(),
  citationsVerified: z.boolean().nullable().optional(),
  orphanCitationsStripped: z.boolean().nullable().optional(),
  releaseManifest: z.record(z.string(), z.unknown()).nullable().optional(),
  provenanceManifest: z.record(z.string(), z.unknown()).nullable().optional(),
  aiProvenance: z.record(z.string(), z.unknown()).nullable().optional(),
  traceId: z.string().nullable().optional(),
  latencyMs: z.number().nullable().optional(),
  modelUsed: z.string().nullable().optional(),
  modelProvider: z.string().nullable().optional(),
  queryTier: z.string().nullable().optional(),
  sereneMindOffer: z.object({
    triggered: z.boolean(),
    level: z.string().optional(),
    confidence: z.number().optional(),
    signals: z.array(z.string()).optional(),
    suggested_response: z.string().optional(),
    teachings_prelude: z.string().optional(),
    requires_consent: z.boolean().optional(),
    offer_reason: z.string().optional(),
    duration_seconds: z.number().optional(),
    custom_meditation: z.object({
      source_teaching: z.string().optional(),
      steps: z.array(z.record(z.string(), z.unknown())),
    }).optional(),
  }).nullable().optional(),
});

const ConversationSchema = z.object({
  id: z.string(),
  startedAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  preview: z.string(),
  messageCount: z.number(),
  messages: z.array(MessageSchema),
  summary: z.string().optional(),
});

export const loadAllFeedback = (): Record<string, MessageFeedback> => {
  try {
    const raw = localStorage.getItem(FEEDBACK_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (typeof parsed !== 'object' || parsed === null) {
        localStorage.removeItem(FEEDBACK_KEY);
        return {};
      }
      // Re-hydrate dates
      for (const key of Object.keys(parsed)) {
        if (parsed[key] && typeof parsed[key] === 'object') {
          parsed[key].timestamp = new Date(parsed[key].timestamp);
        }
      }
      return parsed;
    }
  } catch (e) {
    console.error('Failed to load feedback — clearing corrupted data:', e);
    localStorage.removeItem(FEEDBACK_KEY);
  }
  return {};
};

export interface Conversation {
  id: string;
  startedAt: Date;
  updatedAt: Date;
  preview: string;
  messageCount: number;
  messages: Message[];
  summary?: string;
}

const STORAGE_KEY = 'askmukthiguru_chat_history';
const CONVERSATIONS_KEY = 'askmukthiguru_conversations';
const CURRENT_CONVERSATION_KEY = 'askmukthiguru_current_conversation';
const MAX_CONVERSATIONS_KEY = 'askmukthiguru_max_conversations';
const RETENTION_DAYS_KEY = 'askmukthiguru_retention_days';

let _incognito = false;

export function setIncognitoMode(val: boolean): void {
  _incognito = val;
}

export function isIncognitoMode(): boolean {
  return _incognito;
}

export const getMaxConversations = (): number => {
  try {
    const raw = localStorage.getItem(MAX_CONVERSATIONS_KEY);
    const parsed = raw ? parseInt(raw, 10) : NaN;
    if (!isNaN(parsed) && parsed > 0) return parsed;
  } catch { /* storage is unavailable; use the documented safe default */ }
  return 10;
};

/** Read the user-configured retention window in days (default: 90). */
export const getRetentionDays = (): number => {
  try {
    const raw = localStorage.getItem(RETENTION_DAYS_KEY);
    const parsed = raw ? parseInt(raw, 10) : NaN;
    if (!isNaN(parsed) && parsed > 0) return parsed;
  } catch { /* storage is unavailable; use the documented safe default */ }
  return 90;
};

/** Persist the retention window in days and immediately prune stale conversations. */
export const setRetentionDays = (days: number): void => {
  try {
    const clamped = Math.max(1, Math.min(365, days));
    localStorage.setItem(RETENTION_DAYS_KEY, clamped.toString());
    // Inline purge to avoid forward-reference to purgeConversationsByAge
    const currentId = localStorage.getItem(CURRENT_CONVERSATION_KEY);
    const cutoff = Date.now() - clamped * 24 * 60 * 60 * 1000;
    const raw = localStorage.getItem(CONVERSATIONS_KEY);
    if (!raw) return;
    const all = JSON.parse(raw) as Array<{ id: string; updatedAt: string }>;
    const keep = all.filter(
      (c) => c.id === currentId || new Date(c.updatedAt).getTime() >= cutoff
    );
    if (keep.length < all.length) {
      localStorage.setItem(CONVERSATIONS_KEY, JSON.stringify(keep));
    }
  } catch { /* storage is unavailable; use the documented safe default */ }
};

// Backwards compatible constant for internal use (now derived at runtime)
const MAX_CONVERSATIONS = getMaxConversations();

export const generateId = (): string => {
  const cryptoObj = typeof window !== 'undefined' ? window.crypto : (typeof crypto !== 'undefined' ? crypto : null);
  if (cryptoObj?.randomUUID) {
    return cryptoObj.randomUUID();
  }
  if (cryptoObj?.getRandomValues) {
    const bytes = new Uint8Array(16);
    cryptoObj.getRandomValues(bytes);
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }
  return typeof crypto !== 'undefined' && crypto?.randomUUID ? crypto.randomUUID() : '00000000-0000-4000-8000-000000000000';
};

// Legacy functions for backward compatibility
export const saveChatHistory = (messages: Message[]): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(messages));
  } catch (error) {
    console.error('Failed to save chat history:', error);
  }
};

export const loadChatHistory = (): Message[] => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored) as StoredConversationRecord[];
      const result = z.array(MessageSchema).safeParse(parsed);
      if (!result.success) {
        console.error('Corrupted chat history — clearing:', result.error.message);
        localStorage.removeItem(STORAGE_KEY);
        return [];
      }
      return result.data as Message[];
    }
  } catch (error) {
    console.error('Failed to load chat history — clearing corrupted data:', error);
    localStorage.removeItem(STORAGE_KEY);
  }
  return [];
};

export const clearChatHistory = (): void => {
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch (error) {
    console.error('Failed to clear chat history:', error);
  }
};

// ── Cloud sync ────────────────────────────────────────────────────
// Mirrors a conversation + its messages into Supabase for authenticated users.
// Fire-and-forget: never blocks the local-first save. Failures are logged only.
async function syncConversationToDb(conversation: Conversation): Promise<void> {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    const userId = session?.user?.id;
    if (!userId) return;

    const title = conversation.preview || 'New conversation';
    await supabase.from('conversations').upsert(
      {
        id: conversation.id,
        user_id: userId,
        title,
        preview: title,
        created_at: conversation.startedAt.toISOString(),
        updated_at: conversation.updatedAt.toISOString(),
      },
      { onConflict: 'id' },
    );

    if (!conversation.messages.length) return;
    const { data: existing } = await supabase
      .from('chat_messages')
      .select('id')
      .eq('conversation_id', conversation.id);
    const have = new Set((existing ?? []).map((r) => r.id));
    const toInsert = conversation.messages
      .filter((m) => !have.has(m.id))
      .map((m) => ({
        id: m.id,
        conversation_id: conversation.id,
        role: m.role,
        content: m.content,
        // chat_messages.citations is a Postgres text[] column — project down
        // to bare URLs; title is a display-only enrichment kept in local
        // storage, not persisted to this analytics/backup table.
        citations: m.citations?.length ? m.citations.map((c) => c.url) : null,
        confidence_score: m.confidenceScore ?? null,
        created_at: m.timestamp.toISOString(),
      }));
    if (toInsert.length) {
      await supabase.from('chat_messages').insert(toInsert);
    }
  } catch (e) {
    console.warn('Conversation cloud-sync skipped:', e);
  }
}

const isUuid = (str: string): boolean => {
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  return uuidRegex.test(str);
};

async function readConversationsRaw(): Promise<string | null> {
  return storage.getItem(CONVERSATIONS_KEY);
}

async function writeConversationsRaw(value: string): Promise<void> {
  await storage.setItem(CONVERSATIONS_KEY, value);
}

async function removeConversationsRaw(): Promise<void> {
  await storage.removeItem(CONVERSATIONS_KEY);
}

async function readCurrentIdRaw(): Promise<string | null> {
  return storage.getItem(CURRENT_CONVERSATION_KEY);
}

async function writeCurrentIdRaw(value: string): Promise<void> {
  await storage.setItem(CURRENT_CONVERSATION_KEY, value);
}

type StoredMessageRecord = Record<string, unknown> & { id?: string };
type StoredConversationRecord = Record<string, unknown> & { id?: string; messages?: StoredMessageRecord[] };

export const loadConversations = async (): Promise<Conversation[]> => {
  let stored: string | null = null;
  let currentId: string | null = null;

  try {
    stored = await readConversationsRaw();
    currentId = await readCurrentIdRaw();
  } catch (storageError) {
    console.error('Storage read error — preserving data and degrading gracefully:', storageError);
    return [];
  }

  if (stored) {
    let parsed: StoredConversationRecord[];
    try {
      parsed = JSON.parse(stored);
    } catch (parseError) {
      console.error('Failed to parse conversations JSON — clearing corrupted data:', parseError);
      await removeConversationsRaw().catch(() => {});
      return [];
    }

    if (!Array.isArray(parsed)) {
      console.error('Parsed conversations is not an array — clearing corrupted data');
      await removeConversationsRaw().catch(() => {});
      return [];
    }

    let migrated = false;
    let replacementCurrentId: string | null = null;

    try {
      parsed = parsed.map((conv: StoredConversationRecord) => {
        let convChanged = false;
        let newConvId = conv.id ?? '';

        if (!isUuid(conv.id ?? '')) {
          newConvId = generateId();
          convChanged = true;
          migrated = true;
        }

        if (currentId === (conv.id ?? '') && convChanged) {
          replacementCurrentId = newConvId;
        }

        const messages = (Array.isArray(conv.messages) ? conv.messages : []).map((msg: StoredMessageRecord) => {
          let msgChanged = false;
          let newMsgId = msg.id ?? '';

          if (!isUuid(msg.id ?? '')) {
            newMsgId = generateId();
            msgChanged = true;
            migrated = true;
          }

          if (msgChanged || convChanged) {
            return {
              ...msg,
              id: newMsgId,
            };
          }
          return msg;
        });

        if (convChanged) {
          return {
            ...conv,
            id: newConvId,
            messages,
          };
        } else if (migrated) {
          return {
            ...conv,
            messages,
          };
        }
        return conv;
      });

      if (migrated) {
        await writeConversationsRaw(JSON.stringify(parsed));
      }

      if (replacementCurrentId) {
        await writeCurrentIdRaw(replacementCurrentId);
      }
    } catch (migrationError) {
      console.error('Migration error — preserving data and degrading gracefully:', migrationError);
      return [];
    }

    const result = z.array(ConversationSchema).safeParse(parsed);
    if (!result.success) {
      console.error('Corrupted conversations — clearing:', result.error.message);
      await removeConversationsRaw().catch(() => {});
      return [];
    }
    return result.data as Conversation[];
  }

  return [];
};

export const loadConversation = async (id: string): Promise<Conversation | null> => {
  try {
    const conversations = await loadConversations();
    return conversations.find(c => c.id === id) || null;
  } catch (error) {
    console.error('Failed to load conversation:', error);
  }
  return null;
};

export const saveConversation = async (conversation: Conversation, notify: boolean = true): Promise<void> => {
  if (_incognito) return;
  try {
    const conversations = await loadConversations();
    const existingIndex = conversations.findIndex(c => c.id === conversation.id);

    if (existingIndex >= 0) {
      conversations[existingIndex] = conversation;
    } else {
      conversations.unshift(conversation);
    }

    const trimmed = conversations.slice(0, getMaxConversations());
    await writeConversationsRaw(JSON.stringify(trimmed));

    if (notify) {
      window.dispatchEvent(new CustomEvent('conversation:updated'));
      void syncConversationToDb(conversation);
    }
  } catch (error) {
    console.error('Failed to save conversation:', error);
    throw error;
  }
};


export const deleteConversation = async (id: string): Promise<void> => {
  try {
    const conversations = await loadConversations();
    const filtered = conversations.filter(c => c.id !== id);
    await writeConversationsRaw(JSON.stringify(filtered));
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session?.user?.id) return;
      await supabase.from('chat_messages').delete().eq('conversation_id', id);
      await supabase.from('conversations').delete().eq('id', id);
    } catch (e) {
      console.warn('Cloud delete skipped:', e);
    }
  } catch (error) {
    console.error('Failed to delete conversation:', error);
    throw error;
  }
};

/**
 * Purge conversations older than `days` days from local storage.
 * Never deletes the currently active conversation.
 */
export const purgeConversationsByAge = async (days: number): Promise<void> => {
  try {
    const currentId = await getCurrentConversationId();
    const cutoff = Date.now() - days * 24 * 60 * 60 * 1000;
    const conversations = await loadConversations();
    const keep = conversations.filter(
      (c) => c.id === currentId || new Date(c.updatedAt).getTime() >= cutoff
    );
    if (keep.length < conversations.length) {
      await writeConversationsRaw(JSON.stringify(keep));
    }
  } catch (error) {
    console.error('Failed to purge old conversations:', error);
  }
};

export const renameConversation = async (id: string, newTitle: string): Promise<void> => {
  try {
    const conversations = await loadConversations();
    const index = conversations.findIndex(c => c.id === id);
    if (index >= 0) {
      conversations[index].preview = newTitle;
      conversations[index].updatedAt = new Date();
      await writeConversationsRaw(JSON.stringify(conversations));
      try {
        const { data: { session } } = await supabase.auth.getSession();
        if (!session?.user?.id) return;
        await supabase
          .from('conversations')
          .update({ title: newTitle, preview: newTitle, updated_at: new Date().toISOString() })
          .eq('id', id);
      } catch (e) {
        console.warn('Cloud rename skipped:', e);
      }
    }
  } catch (error) {
    console.error('Failed to rename conversation:', error);
    throw error;
  }
};


export const updateConversationSummary = async (id: string, summary: string): Promise<void> => {
  try {
    const conversations = await loadConversations();
    const index = conversations.findIndex(c => c.id === id);
    if (index >= 0) {
      conversations[index].summary = summary;
      await writeConversationsRaw(JSON.stringify(conversations));
    }
  } catch (error) {
    console.error('Failed to update conversation summary:', error);
    throw error;
  }
};

export const getCurrentConversationId = async (): Promise<string | null> => {
  try {
    return await storage.getItem(CURRENT_CONVERSATION_KEY);
  } catch (error) {
    return null;
  }
};

export const setCurrentConversationId = async (id: string): Promise<void> => {
  try {
    await storage.setItem(CURRENT_CONVERSATION_KEY, id);
  } catch (error) {
    console.error('Failed to set current conversation:', error);
    throw error;
  }
};

export const createNewConversation = (): Conversation => {
  const id = generateId();
  const now = new Date();
  return {
    id,
    startedAt: now,
    updatedAt: now,
    preview: '',
    messageCount: 0,
    messages: [],
  };
};

export const getConversationPreview = (messages: Message[]): string => {
  const firstUserMessage = messages.find(m => m.role === 'user');
  if (firstUserMessage) {
    return firstUserMessage.content.length > 50
      ? firstUserMessage.content.substring(0, 50) + '...'
      : firstUserMessage.content;
  }
  return 'New conversation';
};

// Format relative time
export const formatRelativeTime = (date: Date): string => {
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return 'Yesterday';
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
  return date.toLocaleDateString();
};

// Placeholder responses from the Gurus
export const guruResponses: string[] = [
  "When you are in a beautiful state, you don't just experience life - you become life itself. The separation between you and existence dissolves.",
  "The mind that suffers is the mind that resists what is. Acceptance is not resignation - it is awakening to the present moment.",
  "Your thoughts are not you. They are clouds passing through the sky of consciousness. Watch them, but do not become them.",
  "The heart that is connected feels no isolation. In connection, there is no suffering. In disconnection lies all pain.",
  "Every conflict outside is a reflection of conflict within. When inner peace dawns, outer peace follows naturally.",
  "The beautiful state is not something to achieve - it is what remains when the suffering state is seen through.",
  "When you stop fighting with life, life starts flowing through you. This is the secret of effortless living.",
  "Consciousness is not something you have - it is what you are. Realize this, and the search ends.",
  "The greatest gift you can give another is your own beautiful state. From this state, all right action flows.",
  "Suffering is not what happens to you - it is your relationship with what happens. Transform the relationship, transform the experience.",
];

export const getPlaceholderResponse = (): string => {
  const randomIndex = Math.floor(Math.random() * guruResponses.length);
  return guruResponses[randomIndex];
};
