/**
 * greeting.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Runtime greeting helpers.
 *
 * HOW TO CHANGE GREETING TEXT
 * ────────────────────────────
 * Do NOT edit this file for text changes — edit `greetingConstants.ts` instead.
 * This file only contains logic (time-of-day, persona mapping, visit context).
 *
 * VISIT CONTEXT
 * ─────────────
 * The helpers accept a `GreetingContext` so callers can pass the right bucket:
 *   • "first_visit"      — user has never seen the chat page before
 *   • "return_same_day"  — user opened a second session today
 *   • "return_new_day"   — user is back on a different calendar day (default)
 *
 * Persistence is handled by the caller (profileStorage / useVisitContext hook).
 */

import {
  FIRST_VISIT_SUB_LINES,
  GENERAL_GREETINGS,
  JI_GREETINGS,
  RETURN_NEW_DAY_SUB_LINES,
  RETURN_SAME_DAY_SUB_LINES,
  SADHGURU_GREETINGS,
  type GreetingContext,
  type TimeOfDay,
} from './greetingConstants';

export type { GreetingContext, TimeOfDay };

// ─── Persona sets ─────────────────────────────────────────────────────────────
const JI_PERSONAS = new Set(['sri_preethaji', 'sri_krishnaji', 'general', 'relationship', 'sky']);
const SADHGURU_PERSONAS = new Set(['sadhguru']);

// ─── Time-of-day ─────────────────────────────────────────────────────────────
const MORNING_START_HOUR   = 5;
const AFTERNOON_START_HOUR = 12;
const EVENING_START_HOUR   = 17;
const NIGHT_START_HOUR     = 21;

export const timeOfDay = (date: Date = new Date()): TimeOfDay => {
  const h = date.getHours();
  if (h >= MORNING_START_HOUR   && h < AFTERNOON_START_HOUR) return 'morning';
  if (h >= AFTERNOON_START_HOUR && h < EVENING_START_HOUR)   return 'afternoon';
  if (h >= EVENING_START_HOUR   && h < NIGHT_START_HOUR)     return 'evening';
  return 'night';
};

/** Day-of-year (0–365) — stable rotation seed. */
const dayOfYear = (date: Date): number => {
  const start = new Date(date.getFullYear(), 0, 0);
  return Math.floor((date.getTime() - start.getTime()) / 86_400_000);
};

// ─── Name helpers ─────────────────────────────────────────────────────────────

/** Returns only the first word of a display name. "Harshoda Kolluru" → "Harshoda". */
export const firstName = (name: string): string => {
  const trimmed = (name ?? '').trim();
  return trimmed.split(/\s+/)[0] ?? '';
};

/** Suffix appended after the greeting prefix. Appends "Ji" for Ji-personas. */
export const greetingSuffix = (slug: string | undefined, name: string): string => {
  const first = firstName(name);
  if (slug && JI_PERSONAS.has(slug)) return first ? `, ${first} Ji` : '';
  return first ? `, ${first}` : '';
};

// ─── Greeting prefix ─────────────────────────────────────────────────────────

/**
 * Returns a greeting prefix string chosen from the appropriate pool.
 *
 * @param slug    Persona slug (e.g. 'sri_preethaji', 'sadhguru').
 * @param context Visit context — first_visit | return_same_day | return_new_day.
 * @param date    Date used for time-of-day and rotation (defaults to now).
 */
export const greetingPrefix = (
  slug: string | undefined,
  context: GreetingContext = 'return_new_day',
  date: Date = new Date(),
): string => {
  const tod = timeOfDay(date);
  const day = dayOfYear(date);

  let pool: readonly string[];
  if (slug && SADHGURU_PERSONAS.has(slug)) {
    pool = SADHGURU_GREETINGS[context][tod];
  } else if (slug && JI_PERSONAS.has(slug)) {
    pool = JI_GREETINGS[context][tod];
  } else {
    pool = GENERAL_GREETINGS[context][tod];
  }

  return pool[day % pool.length];
};

// ─── Full greeting ────────────────────────────────────────────────────────────

/**
 * Full display greeting. Examples:
 *   "Good morning, Harshoda Ji"
 *   "Welcome — may this morning be the beginning of something beautiful, Harshoda"
 *
 * Always uses first name only (not full display name).
 */
export const buildGreeting = (
  slug: string | undefined,
  name: string,
  context: GreetingContext = 'return_new_day',
  date: Date = new Date(),
): string => `${greetingPrefix(slug, context, date)}${greetingSuffix(slug, name)}`;

// ─── Sub-lines ────────────────────────────────────────────────────────────────

/**
 * Short line shown beneath the main greeting h2.
 * Changes based on visit context.
 */
export const buildGreetingSubline = (
  context: GreetingContext = 'return_new_day',
  date: Date = new Date(),
): string => {
  const day = dayOfYear(date);
  let pool: readonly string[];
  if (context === 'first_visit')      pool = FIRST_VISIT_SUB_LINES;
  else if (context === 'return_same_day') pool = RETURN_SAME_DAY_SUB_LINES;
  else                                 pool = RETURN_NEW_DAY_SUB_LINES;
  return pool[day % pool.length];
};
