apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mukthiguru.fullname" . }}-config
  labels:
    {{- include "mukthiguru.labels" . | nindent 4 }}
data:
  {{- with .Values.env }}
  {{- range . }}
  {{- if .value }}
  {{ .name }}: {{ .value | toString | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  OLLAMA_URL: "http://127.0.0.1:11434"
  QDRANT_URL: "http://{{ include "mukthiguru.fullname" . }}-qdrant:6333"
  NEO4J_BOLT_URL: "bolt://{{ include "mukthiguru.fullname" . }}-neo4j:7687"
  NEO4J_USER: "neo4j"
  REDIS_URL: "redis://:{{ .Values.redis.auth.password }}@{{ include "mukthiguru.fullname" . }}-redis-master:6379"
  JAEGER_AGENT_HOST: "{{ include "mukthiguru.fullname" . }}-jaeger"
  JAEGER_AGENT_PORT: "16686"
  ENVIRONMENT: "{{ .Values.environment | default "production" }}"
