import { Link } from 'react-router-dom';
import { Sparkles } from 'lucide-react';
import { usePageMeta } from '@/hooks/usePageMeta';

const PrivacyPage = () => {
  usePageMeta({
    title: 'Privacy Policy — AskMukthiGuru',
    description: 'How AskMukthiGuru handles your data: minimum collection, no third-party sharing, full export and deletion rights under DPDP Act and GDPR.',
    canonical: 'https://askmukthiguru.lovable.app/privacy',
  });
  return (
  <main className="min-h-dvh bg-background text-foreground px-4 py-10">
    <div className="max-w-2xl mx-auto space-y-6">
      <Link to="/" className="inline-flex items-center gap-2 text-ojas hover:underline">
        <Sparkles className="w-4 h-4" /> AskMukthiGuru
      </Link>
      <h1 className="text-2xl font-semibold">Privacy Policy</h1>
      <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      <section className="prose prose-sm dark:prose-invert max-w-none">
        <p>
          AskMukthiGuru is a privacy-first spiritual companion. We collect the minimum data
          required to deliver the experience: your email (for authentication), your conversation
          messages (so you can pick up where you left off), and meditation session counts (to show
          your streak).
        </p>
        <h2>What we store</h2>
        <ul>
          <li>Email address &amp; encrypted password (or Google profile) — for sign-in.</li>
          <li>Chat conversations and messages — visible only to you (Row-Level Security).</li>
          <li>Meditation sessions — visible only to you.</li>
        </ul>
        <h2>What we never do</h2>
        <ul>
          <li>Sell or share your data with third parties.</li>
          <li>Use your conversations to train external models.</li>
          <li>Show you advertisements.</li>
        </ul>
        <h2>Your rights (DPDP Act / GDPR)</h2>
        <p>
          You may request export or deletion of your data at any time by emailing
          <a href="mailto:privacy@askmukthiguru.com"> privacy@askmukthiguru.com</a>.
        </p>
        <h2>AI disclosure</h2>
        <p>
          Responses are generated by an AI grounded in publicly available teachings of
          Sri Preethaji and Sri Krishnaji. AskMukthiGuru is not a substitute for professional
          mental-health care.
        </p>
      </section>
      <Link to="/" className="text-sm text-ojas hover:underline">← Back to home</Link>
    </div>
  </main>
  );
};

export default PrivacyPage;
