import { Link } from 'react-router-dom';
import { Sparkles } from 'lucide-react';
import { usePageMeta } from '@/hooks/usePageMeta';

const TermsPage = () => {
  usePageMeta({
    title: 'Terms of Service — AskMukthiGuru',
    description: 'Terms governing personal, non-commercial use of AskMukthiGuru. AI guidance is not a substitute for professional mental-health care.',
    canonical: 'https://askmukthiguru.lovable.app/terms',
  });
  return (
  <main className="min-h-screen bg-background text-foreground px-4 py-10">
    <div className="max-w-2xl mx-auto space-y-6">
      <Link to="/" className="inline-flex items-center gap-2 text-ojas hover:underline">
        <Sparkles className="w-4 h-4" /> AskMukthiGuru
      </Link>
      <h1 className="text-2xl font-semibold">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      <section className="prose prose-sm dark:prose-invert max-w-none">
        <h2>Use of the service</h2>
        <p>
          AskMukthiGuru offers AI-assisted spiritual guidance for personal reflection only. By
          using the service you agree to use it in good faith and not for any harmful, abusive,
          or illegal purpose.
        </p>
        <h2>Not medical or mental-health advice</h2>
        <p>
          Responses are generated by an AI and are <strong>not</strong> a substitute for
          professional mental-health care. If you are in crisis, please contact a qualified
          professional or a crisis helpline immediately. India: iCall +91-9152987821, Vandrevala
          Foundation 1860-2662-345.
        </p>
        <h2>Intellectual property</h2>
        <p>
          Teachings cited are the intellectual property of Sri Preethaji, Sri Krishnaji and AUM,
          used here for educational and reflective purposes with attribution.
        </p>
        <h2>Account &amp; termination</h2>
        <p>
          You may delete your account at any time. We may suspend accounts that violate these
          Terms or applicable law.
        </p>
        <h2>Changes</h2>
        <p>
          We may update these Terms; continued use after a change constitutes acceptance of the
          new Terms.
        </p>
      </section>
      <Link to="/" className="text-sm text-ojas hover:underline">← Back to home</Link>
    </div>
  </main>
);

export default TermsPage;
