import csv,json,hashlib,datetime
from pathlib import Path
from collections import Counter,defaultdict
root=Path('scripts/ingestion/reviews/correction_research_run'); x=json.loads((root/'correction_candidates.json').read_text()); summary=json.loads((root/'inventory_summary.json').read_text())

def classify(r):
 rule=r.get('rule_id',''); mt=r.get('matched_text','')
 if rule in {'DOCTRINE_EKAM','DOCTRINE_SRI_PREETHAJI','DOCTRINE_SRI_KRISHNAJI','DOCTRINE_SRI_PREETHAJI_SRI_KRISHNAJI'}: return 'confirmed_canonical_name','high','Apply canonical movement spelling; source and official pages agree.'
 if rule=='DOCTRINE_BEAUTIFUL_STATE': return 'confirmed_style_normalization','high','Official movement materials use Beautiful State as a named teaching; source subtitles may remain lowercase.'
 if rule=='DOCTRINE_FOUR_SACRED_SECRETS': return 'confirmed_style_normalization','high','Official title is The Four Sacred Secrets.'
 if rule=='DOCTRINE_SOUL_SYNC':
  return ('confirmed_phonetic_correction' if mt.lower()=='soul sink' else 'confirmed_spacing_normalization'),'high','Primary YouTube evidence consistently uses soul sync; source branding uses the two-word form.'
 if rule=='DOCTRINE_I_CONSCIOUSNESS':
  return ('confirmed_phonetic_correction' if mt.lower()=='eye consciousness' else 'confirmed_style_normalization'),'high','Primary video evidence uses I consciousness in an I/one-consciousness contrast; Eye is a phonetic error.'
 if rule=='DOCTRINE_DEEKSHA': return 'project_style_normalization','medium','Primary video uses Deeksha, while Diksha is also an established transliteration; retain as project-specific canonicalization.'
 if rule=='DOCTRINE_MUKTHI': return 'manual_review_transliteration','medium','Primary video evidence uses Mukti; the corpus canonical Mukthi is a project preference, not uniquely established by external evidence.'
 if rule in {'DOCTRINE_SAMSKARA','DOCTRINE_CHAKRA'}: return 'manual_review_grammar_and_number','medium','Authoritative usage supports the base term, but plural English forms samskaras/chakras can be valid; do not auto-collapse without sentence-level review.'
 if rule=='DOCTRINE_SUFFERING_STATE': return 'manual_review_style_normalization','medium','The phrase is documented in related teaching material, but source subtitles may use lowercase and current official site also uses Stressful State; verify local context.'
 return 'manual_review','low','Needs evidence review.'
for r in x:
 d,c,why=classify(r); r.update({'disposition':d,'confidence':c,'evidence_rationale':why,'timestamp':f"{r['start_seconds']:.2f}-{r['end_seconds']:.2f}" if isinstance(r.get('start_seconds'),(int,float)) and isinstance(r.get('end_seconds'),(int,float)) else None})
with (root/'correction_findings.json').open('w') as f: json.dump(x,f,indent=2,ensure_ascii=False)
fields=['candidate_id','video_id','package_path','ledger_index','rule_id','segment_id','char_start','char_end','start_seconds','end_seconds','timestamp','matched_text','replacement','disposition','confidence','quality_state','reason','local_issues','segment_text','original_segment_text','evidence_rationale']
with (root/'correction_locations.csv').open('w',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows({k:r.get(k) for k in fields} for r in x)
by=Counter((r['rule_id'],r['matched_text'],r['replacement'],r['disposition']) for r in x); disp=Counter(r['disposition'] for r in x); rules=defaultdict(list)
for r in x: rules[r['rule_id']].append(r)
refs=['https://www.theonenessmovement.org/','https://www.ekam.org/sri-preethaji-sri-krishnaji','https://www.theonenessmovement.org/the-beautiful-state','https://www.youtube.com/watch?v=1e0yk20hF7Y','https://www.youtube.com/watch?v=4ytgjpow498','https://www.youtube.com/watch?v=07NOYJmkkFo','https://www.youtube.com/watch?v=4HRL8IxADhg','https://www.merriam-webster.com/dictionary/samskara','https://www.merriam-webster.com/dictionary/chakra','https://www.onecommune.com/blog/the-beautiful-state-with-preethaji']
md=[]; md+=['# Transcript Correction Research Report','',f"**Scope:** all {summary['package_count']} package directories and all {summary['candidate_count']} ledger locations; canonical corpus files were not edited.",'', '## Executive conclusion','',f"The deterministic pass found **{len(x)} exact correction locations** across **{sum(1 for r in x if r['video_id'])} location records** and **{len(rules)} rule families**. The candidate spans are locally valid under the corpus contract: ledger offsets are measured against `original_segment_text`, while canonical segments contain the corrected text. There were {summary['issue_counts'].get('missing_required',0)} package directories with missing required artifacts; these are separate integrity/coverage findings.",'',f"The strongest correction families are the movement’s canonical names and branding terms: Ekam, Sri Preethaji, Sri Krishnaji, Beautiful State, Soul Sync, Four Sacred Secrets, and I-Consciousness. Official movement pages use those spellings and forms [1] [2] [3]. Primary-source YouTube analysis also found Ekam, Sri Preethaji, Sri Krishnaji, Mukti, and Deeksha in a representative video [4], consistently found the two-word spelling Soul Sync and no spoken “soul sink” [5], and found I consciousness—not Eye Consciousness—in the relevant conceptual contrast [7].",'', '## Disposition summary','', '| Disposition | Locations | Interpretation |','|---|---:|---|']
labels={'confirmed_canonical_name':'Apply canonical movement spelling','confirmed_style_normalization':'Apply named-term capitalization/title normalization','confirmed_phonetic_correction':'Apply correction; primary source supports spoken term','confirmed_spacing_normalization':'Apply spacing normalization; preserve source wording in evidence','project_style_normalization':'Use only if the project style guide requires this spelling','manual_review_transliteration':'Do not auto-apply; resolve project transliteration policy','manual_review_grammar_and_number':'Do not auto-apply; review singular/plural sentence context','manual_review_style_normalization':'Review against local context and current terminology'}
for k,n in disp.most_common(): md.append(f'| {k} | {n} | {labels.get(k,"")} |')
md += ['', '## Rule-family findings','', '| Rule | Locations | Current variants | Proposed canonical form | Disposition |', '|---|---:|---|---|---|']
for key,rows in sorted(rules.items()):
 variants=Counter(r['matched_text'] for r in rows); reps=Counter(r['replacement'] for r in rows); d=Counter(r['disposition'] for r in rows).most_common(1)[0][0]
 md.append(f"| {key} | {len(rows)} | {', '.join(f'{a} ({b})' for a,b in variants.items())} | {', '.join(reps)} | {d} |")
md += ['', '## Important research interpretation','', 'The corpus ledger labels every entry as a phonetic correction, but the second research pass shows that not every entry is a phonetic error. Beautiful State, Four Sacred Secrets, and Soul Sync are often **branding or style normalizations**. The primary video evidence supports “soul sync” and rejects “soul sink” [5].', '', 'The Mukti→Mukthi family requires a project-level decision: a representative primary video visibly and audibly uses **Mukti**, while the repository’s curated map prefers **Mukthi** [4]. This is not enough evidence for a universal correction. The Samskaras→Samskara and Chakras→Chakra families also require sentence-level review because authoritative English usage recognizes the base terms and valid plural forms [8] [9]; several corrected sentences can become grammatically awkward if a plural is collapsed to singular.', '', 'The exact places are in `correction_locations.csv` and `correction_findings.json`. Each row includes the video ID, segment ID, start/end timestamps, original character span, current text, proposed text, quality state, and disposition. A compact sample is shown below.','', '| Video ID | Segment | Timestamp | Current text | Proposed | Disposition |', '|---|---|---:|---|---|---|']
for r in x[:25]: md.append(f"| `{r['video_id']}` | `{r['segment_id']}` | {r['timestamp']} | `{r['matched_text']}` | `{r['replacement']}` | {r['disposition']} |")
md += ['', '> For the complete end-to-end list, use the attached CSV; the table above is only a readable sample.', '', '## Corpus and validation notes','',f"The corpus contains {summary['package_count']} package directories. {summary['packages_with_ledgers']} packages contain one or more correction-ledger entries, totaling {summary['candidate_count']} locations. The deterministic validator found no ledger span, segment lookup, or original-text mismatch after applying the documented offset semantics. It did find {summary['issue_counts'].get('missing_required',0)} packages with missing required files; those packages should not be promoted without a separate integrity review.", '', '## References']
for i,u in enumerate(refs,1): md.append(f'[{i}]: {u}')
(root/'correction_report.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
# evidence register
reg=['# Research Evidence Register','', '| Evidence | Finding | Use in adjudication |','|---|---|---|', '| Official Oneness Movement homepage [1] | Uses Sri Preethaji & Sri Krishnaji, Beautiful State, Soul Sync, and Ekam. | Supports canonical names and branded forms. |', '| Official Ekam biography [2] | Uses Sri Preethaji & Sri Krishnaji, The Four Sacred Secrets, and Samskara. | Supports names/title and base-term spelling. |', '| Official Beautiful State page [3] | Uses The Beautiful State as a named programme/teaching. | Supports title-case normalization, not necessarily audio phonetics. |', '| YouTube 1e0yk20hF7Y [4] | At 00:02–00:09, primary analysis identifies Mukti, Sri Krishnaji, Sri Preethaji, Ekam, and Deeksha. | Confirms source spellings; leaves Mukthi vs Mukti as a project-policy question. |', '| YouTube 4ytgjpow498 [5] | Repeated audio/on-screen evidence uses “soul sync”; no “soul sink” found. | Confirms soul sink corrections and two-word spacing normalization. |', '| YouTube 07NOYJmkkFo [6] | Speaker uses “beautiful state” and “suffering” in lowercase subtitles. | Shows some ledger changes are style normalization rather than phonetic correction. |', '| YouTube 4HRL8IxADhg [7] | Uses “I consciousness” in contrast with “one consciousness”; Eye Consciousness is a phonetic error in this context. | Confirms I-Consciousness corrections, especially eye consciousness. |', '| Merriam-Webster samskara [8] | Defines samskara and recognizes plural -s. | Requires manual review before collapsing samskaras to singular. |', '| Merriam-Webster chakra [9] | Defines chakra and recognizes ordinary English plural chakras. | Requires manual review before collapsing chakras to singular. |', '| One Commune transcript [10] | Uses “beautiful state,” “suffering state,” Soul Sync practice, and Akom as quoted context. | Supports terminology context while showing transliteration variation. |', '', '## Research limitations','', 'The YouTube analysis is multimodal evidence rather than a verbatim transcript; timestamps and quotes should be treated as validation evidence, not as a replacement for the canonical segments. External sources establish standard or project usage but cannot override the speaker’s actual utterance. Regional-language pronunciation, capitalization, and transliteration remain human-review cases where the evidence does not uniquely determine one form.','', '## References']
for i,u in enumerate(refs,1): reg.append(f'[{i}]: {u}')
(root/'research_evidence_register.md').write_text('\n'.join(reg)+'\n',encoding='utf-8')
# manifest
manifest={'generated_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'package_count':summary['package_count'],'candidate_count':len(x),'rule_family_count':len(rules),'disposition_counts':dict(disp),'corpus_modified':False,'outputs':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [root/'correction_report.md',root/'correction_locations.csv',root/'correction_findings.json',root/'research_evidence_register.md']}}
(root/'review_run_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({'locations':len(x),'rules':len(rules),'dispositions':dict(disp)}))
