#!/usr/bin/env node
/**
 * i18n_sync.mjs — English (src/locales/en.json) is the only file humans edit.
 *
 *   npm run i18n:sync      add / edit / delete in en.json  ->  all 13 locales follow
 *   npm run i18n:check     no network; fails if any locale is missing a key, has an
 *                          extra key, is stale vs. an edited English value, still
 *                          holds English, or broke a {{placeholder}} / helpline number
 *
 * sync needs OPENROUTER_API_KEY (OpenRouter only). Model: I18N_MODEL
 * (default anthropic/claude-sonnet-4.5). Flags: --dry-run, --locale=hi,te,
 * --bootstrap (record current English hashes without translating; only valid
 * when `--check` would otherwise pass).
 *
 * Never touched: teacher quotes (keys ending in `quote`), anything outside
 * src/locales. Safety strings are listed in docs/i18n/SAFETY_MACHINE_TRANSLATED.md.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  TARGET_LOCALES, SAFETY_KEY_RE, flatten, patchNested, hashValue, diagnoseLocale, keysToTranslate,
  validateTranslation, buildPrompt, isProtected,
} from './i18n/lib.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const LOCALES_DIR = join(ROOT, 'src', 'locales');
const MANIFEST = join(ROOT, 'scripts', 'i18n', 'source-hashes.json');
const SAFETY_REPORT = join(ROOT, 'docs', 'i18n', 'SAFETY_MACHINE_TRANSLATED.md');
const BATCH = 25;

const args = process.argv.slice(2);
const flag = (n) => args.includes(`--${n}`);
const optVal = (n) => args.find((a) => a.startsWith(`--${n}=`))?.split('=')[1];
const only = optVal('locale')?.split(',');
const locales = only ?? TARGET_LOCALES;

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));
const enNested = readJson(join(LOCALES_DIR, 'en.json'));
const enFlat = flatten(enNested);
const enKeys = Object.keys(enFlat);
let manifest = existsSync(MANIFEST) ? readJson(MANIFEST).hashes ?? {} : {};
const currentHashes = Object.fromEntries(enKeys.map((k) => [k, hashValue(enFlat[k])]));
const loadLocale = (l) => flatten(readJson(join(LOCALES_DIR, `${l}.json`)));

function report() {
  let bad = 0;
  for (const l of locales) {
    const d = diagnoseLocale(enFlat, loadLocale(l), manifest);
    for (const [kind, list] of Object.entries(d)) {
      if (!list.length) continue;
      bad += list.length;
      console.error(`[fail] ${l}: ${list.length} ${kind}: ${list.slice(0, 5).join(', ')}${list.length > 5 ? ', …' : ''}`);
    }
  }
  return bad;
}

if (flag('check')) {
  const bad = report();
  if (bad) {
    console.error(`\ni18n check FAILED (${bad} problems). English is the source: run \`npm run i18n:sync\` (needs OPENROUTER_API_KEY) and commit the result.`);
    process.exit(1);
  }
  console.log(`i18n check OK: ${enKeys.length} keys in sync across ${TARGET_LOCALES.length} locales.`);
  process.exit(0);
}

function saveManifest() {
  writeFileSync(MANIFEST, JSON.stringify({ note: 'sha256/12 of each English value at last sync. Generated by scripts/i18n_sync.mjs; do not edit.', hashes: currentHashes }, null, 1) + '\n');
}

function writeSafetyReport() {
  const keys = enKeys.filter((k) => SAFETY_KEY_RE.test(k) || SAFETY_KEY_RE.test(enFlat[k]));
  const rows = keys.map((k) => `| \`${k}\` | ${enFlat[k].replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`);
  writeFileSync(SAFETY_REPORT, [
    '# Safety/crisis UI strings: machine-translated, NOT native-reviewed',
    '',
    `Generated by \`scripts/i18n_sync.mjs\`. These ${keys.length} English keys touch crisis/safety copy.`,
    `All ${TARGET_LOCALES.length} other locales are machine translations (accepted risk, owner decision 2026-10-08: native reviewers unavailable).`,
    'Helpline numbers and digits are enforced identical to English by the sync validator.',
    '',
    '| Key | English (authoritative) |', '|---|---|', ...rows, '',
  ].join('\n'));
}

async function callModel(localeCode, items) {
  const key = process.env.OPENROUTER_API_KEY;
  if (!key) throw new Error('OPENROUTER_API_KEY is not set');
  const res = await fetch((process.env.I18N_API_URL || 'https://openrouter.ai/api/v1/chat/completions'), {
    method: 'POST',
    headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: process.env.I18N_MODEL || 'anthropic/claude-sonnet-4.5',
      temperature: 0,
      response_format: { type: 'json_object' },
      messages: buildPrompt(localeCode, items),
    }),
  });
  if (!res.ok) throw new Error(`OpenRouter ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const text = (await res.json()).choices?.[0]?.message?.content ?? '{}';
  return JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g, ''));
}

async function translateKeys(l, keys) {
  const done = {};
  let pending = keys;
  for (let attempt = 1; attempt <= 3 && pending.length; attempt++) {
    const failed = [];
    for (let i = 0; i < pending.length; i += BATCH) {
      const slice = pending.slice(i, i + BATCH);
      const got = await callModel(l, Object.fromEntries(slice.map((k) => [k, enFlat[k]])));
      for (const k of slice) {
        const why = validateTranslation(k, enFlat[k], got[k]);
        if (why) { failed.push(k); console.warn(`  ${l} ${k}: rejected (${why}), attempt ${attempt}`); }
        else done[k] = got[k];
      }
    }
    pending = failed;
  }
  if (pending.length) throw new Error(`${l}: could not produce valid translations for ${pending.join(', ')}`);
  return done;
}

if (flag('bootstrap')) {
  manifest = currentHashes; // judge sync state as if English were unchanged
  const bad = report();
  if (bad) { console.error('Refusing to bootstrap: locales are not in sync with English.'); process.exit(1); }
  saveManifest(); writeSafetyReport();
  console.log('Recorded current English hashes.'); process.exit(0);
}

let failed = false;
const nextFlat = {};
for (const l of locales) {
  const flat = loadLocale(l);
  const d = diagnoseLocale(enFlat, flat, manifest);
  const updates = {};
  const todo = keysToTranslate(d);
  const protectedMissing = d.missing.filter(isProtected);
  if (protectedMissing.length) {
    console.error(`[fail] ${l}: protected teacher-content keys missing, add them by hand (never machine-translated): ${protectedMissing.join(', ')}`);
    failed = true;
  }
  console.log(`${l}: ${todo.length} to translate, ${d.extra.length} to delete`);
  if (flag('dry-run')) continue;
  try {
    Object.assign(updates, await translateKeys(l, todo));
  } catch (e) { console.error(`[fail] ${e.message}`); failed = true; continue; }
  nextFlat[l] = { updates, removals: d.extra };
}
if (failed) { console.error('i18n sync FAILED; nothing was written.'); process.exit(1); }
if (flag('dry-run')) process.exit(0);

for (const [l, { updates, removals }] of Object.entries(nextFlat)) {
  const file = join(LOCALES_DIR, `${l}.json`);
  writeFileSync(file, JSON.stringify(patchNested(readJson(file), updates, removals), null, 2) + '\n');
}
if (!only) saveManifest();
writeSafetyReport();
console.log(`i18n sync done for ${Object.keys(nextFlat).join(', ')}.`);
