{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "mukthiguru.backend.fullname" . }}-vault-kek
  labels:
    {{- include "mukthiguru.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  data:
    - secretKey: {{ .Values.externalSecret.data.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.data.remoteRef.key }}
        property: {{ .Values.externalSecret.data.remoteRef.property }}
{{- end }}
