{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mukthiguru.backend.fullname" . }}-pdb
  labels:
    {{- include "mukthiguru.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "mukthiguru.selectorLabels" . | nindent 6 }}
{{- end }}